version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: gym-postgres
    environment:
      - POSTGRES_DB=gym_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d gym_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    container_name: gym-backend
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.multistage
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://db:5432/gym_db
      - QUARKUS_DATASOURCE_USERNAME=postgres
      - QUARKUS_DATASOURCE_PASSWORD=postgres
      - QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION=validate
      - QUARKUS_LIQUIBASE_MIGRATE_AT_START=true
    depends_on:
      db:
        condition: service_healthy

  frontend:
    container_name: gym-frontend
    build:
      context: ../project-02
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend

  prometheus:
    image: prom/prometheus:latest
    container_name: gym-prometheus
    volumes:
      - ./src/main/resources/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "9090:9090"
    depends_on:
      - backend

  grafana:
    image: grafana/grafana:latest
    container_name: gym-grafana
    volumes:
      - ./src/main/resources/monitoring/grafana/provisioning:/etc/grafana/provisioning
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  postgres-data:
  prometheus-data:
  grafana-data:
