# Disable Hibernate ORM and the datasource by default for local dev
# If you need a real database, set `quarkus.datasource.jdbc.url`, `quarkus.datasource.username`
# and `quarkus.datasource.password` and remove or set the properties below to false.
quarkus.hibernate-orm.active=false
quarkus.datasource.enabled=false

